import './globals.css'
import { Inter } from 'next/font/google'
import { StoreProvider } from '@/redux/store/storeProvider'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Билетопоиск',
  description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
    		<body className={inter.className}>
        		<StoreProvider>
          			<header><Header /></header>
          			{children}
        			<footer><Footer/></footer>
        		</StoreProvider>
    		</body>
    	</html>
	)
}
